server:
  port: "8080"

database:
  user: root
  password: z3gf4wf5b
  host: 127.0.0.1
  port: "3306"
  database: turtle_soup

deepseek:
  secret_key: sk-7cfb507aa8f84d919ad3afa9100af450
  domain: https://api.deepseek.com